# Generated by Django 5.2.4 on 2025-07-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='user_id',
            new_name='user',
        ),
    ]
